pages.staff='Account & staff';iconPaths.staff=iconPaths.people;
const desktopRender=render;
render=function(){if(S?.online){$('.sidebar-bottom .local-dot span').textContent='Online workspace · '+S.web_user.role;$('#sync-status').textContent='Shared business · offline PCs supported';}if(page==='staff'){const u=S.web_user;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.getAttribute('onclick')==="navTo('staff')"));$('#page-label').textContent='Account & staff';$('#main').innerHTML=heading('TEAM WORKSPACE','Your account & team.',`${esc(u.name)} · ${esc(u.role)} · ${esc(u.location)}`,`<button class="btn secondary" onclick="signOut()">Sign out</button>`)+(u.role==='owner'?`<div class="card"><div class="card-head"><h2>Staff accounts</h2><button class="btn" onclick="staffForm()">＋ Add account</button></div><div id="staff-list" class="card-content">Loading…</div></div><div class="card" style="margin-top:20px"><div class="card-head"><h2>Offline PCs</h2><a class="btn secondary small" href="/downloads/AlHidayaTraders-Setup-1.0.0.exe">Download Windows 1.0.0</a><button class="btn gold" onclick="pairCodeForm()">Connect a Windows PC</button></div><div id="peer-list" class="card-content">Loading…</div></div>`:'<div class="notice">Your permissions are enforced by the server. Contact the owner to change your role or assigned location.</div>');if(u.role==='owner'){loadStaff();loadPeers();}return}desktopRender();if(S?.online){$('.sidebar-bottom .local-dot span').textContent='Online workspace · '+S.web_user.role;$('#sync-status').textContent='Shared business · internet required';}}
async function loadStaff(){const r=await fetch('/api/users');if(!r.ok)return;const users=await r.json();$('#staff-list').innerHTML=table(['Name / username','Role','Location','Status',''],users.map(u=>`<tr><td>${esc(u.name)}<small>${esc(u.username)}</small></td><td>${esc(u.role)}</td><td>${esc(u.location)}</td><td>${u.active?'Active':'Disabled'}</td><td><button class="text-btn" onclick="staffPassword(${u.id})">Reset password</button>${u.id!==S.web_user.id?`<button class="text-btn" onclick="staffActive(${u.id},${!u.active})">${u.active?'Disable':'Enable'}</button>`:''}</td></tr>`))}
function staffForm(){formModal('Add staff account',`${field('Name','name','','text','required')}${field('Username','username','','text','required')}${field('Password (12+ characters)','password','','password','minlength="12" required autocomplete="new-password"')}${dropdown('Role','role',['manager','cashier','viewer'],'cashier')}${dropdown('Default location','location',['Warehouse','Outlet'],'Warehouse')}<div class="help">Manager handles shop operations. Cashier bills, creates customers and records expenses. Viewer reads records. Owner manages settings, access and recovery.</div>`,async data=>{await api('staff_user',data);await loadStaff();toast('Staff account created.')})}
function staffPassword(id){formModal('Reset staff password',field('New password (12+ characters)','password','','password','minlength="12" required autocomplete="new-password"'),async data=>{await api('staff_password',{...data,id});toast('Password changed. Existing sessions signed out.');if(id===S.web_user.id)location.href='/login'})}
async function staffActive(id,active){try{await api(active?'staff_enable':'staff_disable',{id});await loadStaff()}catch(e){toast(e.message,true)}}
async function signOut(){await api('logout',{});location.href='/login'}
runSync=function(){navTo('staff')};closeApp=function(){signOut()};
const desktopSettings=settings;
settings=function(){if(!S.online)return desktopSettings();if(S.web_user.role!=='owner')return heading('BUSINESS SETTINGS','Owner access required.','Business details and GST are managed by the owner.')+`<button class="btn secondary" onclick="navTo('staff')">Account & staff</button>`;const s=S.settings;return heading('BUSINESS SETTINGS','Your business online.','Shared business records for the website and paired offline PCs.')+`<form id="settings-form"><div class="card card-content"><div class="form-grid">${field('Business name','name',s.name,'text','required')}${field('Phone','phone',s.phone)}${field('Business address','address',s.address)}${field('GSTIN','gstin',s.gstin)}${field('State code','state',s.state)}${field('Invoice prefix','invoice_prefix',s.invoice_prefix)}</div><label class="check"><input type="checkbox" name="gst_enabled" ${s.gst_enabled?'checked':''}> Enable regular-registration GST</label>${dropdown('Print layout','printer',['80','58','A4'],s.printer)}<div id="settings-error" class="error"></div><button class="btn gold" style="margin-top:20px">Save settings</button></div></form><div class="notice" style="margin-top:20px">The desktop app remains the offline option. This website requires internet. Every paired Windows node has full business operations offline and exchanges saved changes when connected. WhatsApp delivery requires a valid sender and approved templates. Scheduling runs while the sender is online.</div><div class="actions" style="margin-top:15px"><button class="btn secondary" onclick="navTo('staff')">Manage staff accounts</button><a class="btn secondary" href="/api/backup-bundle" download>Download backup with photos</a></div>`}
const cloudLoad=load;
load=async function(){await cloudLoad();if(S?.online){const u=S.web_user;if(!$('#online-account')){const btn=document.createElement('button');btn.id='online-account';btn.className='btn secondary small';btn.textContent='Account';btn.onclick=()=>navTo('staff');$('.header-right').append(btn)}if(u.role==='owner'&&!$('#online-location')){const select=document.createElement('select');select.id='online-location';select.style.cssText='width:120px;padding:6px';select.innerHTML=['Warehouse','Outlet'].map(l=>`<option ${u.location===l?'selected':''}>${l}</option>`).join('');select.onchange=async()=>{try{await api('location',{location:select.value});cart=[];window.saleParty='';await load()}catch(e){toast(e.message,true)}};$('.header-right').prepend(select)}if($('#online-location'))$('#online-location').value=u.location;}}

async function loadPeers(){const r=await fetch('/api/peers');if(!r.ok)return;const rows=await r.json();$('#peer-list').innerHTML=`<div class="help">Every paired PC has the same business functions. Location is a default for transactions. Changes exchange when connected; competing offline transactions are flagged for review.</div>`+table(['PC','Location','Last contact','Status',''],rows.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.location)}</td><td>${p.last_contact?esc(new Date(p.last_contact).toLocaleString()):'Not yet'}</td><td>${p.active?'Connected':'Disabled'}</td><td>${p.active?`<button class="text-btn" onclick="disablePeer('${esc(p.device_id)}')">Disable sync</button>`:`<button class="text-btn" onclick="enablePeer('${esc(p.device_id)}')">Enable sync</button>`}</td></tr>`))}
function pairCodeForm(){formModal('Connect a Windows PC',`${dropdown('PC location','location',[{value:'Warehouse',label:'Warehouse — trading and retail'},{value:'Outlet',label:'Outlet — takeaway café'}],'Warehouse')}<div class="help">The Windows app must be version 1.0.0 or newer. Only join with disposable sample data. Every PC can perform every business operation, online or offline. This code works for one PC and expires after 10 minutes.</div>`,async data=>{const r=await api('pair-code',data);await load();openModal('Pairing code — valid for 10 minutes',`<p>In the Windows app open Settings → Connect to online business.</p>${field('Server address','server',location.origin,'text','readonly')}${field('Pairing code','pairing',r.code,'text','readonly')}<p>Default location: ${esc(r.location)}. Full business operations are available.</p><div class="help">Keep this code private. Close this window after pairing. Existing Windows sample records are backed up before replacement.</div>`);},'Generate code')}
async function disablePeer(device_id){try{const r=await api('peer-disable',{device_id});await loadPeers();toast(r.message)}catch(e){toast(e.message,true)}}

async function enablePeer(device_id){try{const r=await api('peer-enable',{device_id});await loadPeers();toast(r.message)}catch(e){toast(e.message,true)}}
